apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/OleksandrTimoshenko/certified-kubernetes-administrator-course
    targetRevision: app_deploy
    path: kubeadm-clusters/virtualbox/k8s/deployment
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
