
apiVersion: v2
name: ingress
description: A Helm chart for Ingress Controller
type: application
version: 0.1.0
appVersion: 1.16.0
keywords:
  - ingress
  - nginx
  - api-gateway
home: https://github.com/wkrzywiec/k8s-helm-helmfile/tree/master/helm
maintainers:
  - name: Wojtek Krzywiec
    url: https://github.com/wkrzywiec
# Since I am configuring my ingress controller in ingress-nginx namespace where the cluster IP is set, I don't need this one yet.
#dependencies:
#  - name: nginx-ingress
#    version: 1.36.0
#    repository: https://charts.helm.sh/stable