apiVersion: v2
name: ingress-nginx
description: Ingress controller for Kubernetes using NGINX as a reverse proxy and load balancer
type: application

# Версия самого Helm chart (твоя версия чарта)
version: 4.14.1

# Версия приложения (Ingress-NGINX Controller)
appVersion: "1.14.1"

keywords:
  - ingress
  - nginx
  - ingress-controller
  - reverse-proxy
  - load-balancer

home: https://kubernetes.github.io/ingress-nginx/

sources:
  - https://github.com/kubernetes/ingress-nginx

maintainers:
  - name: Kubernetes SIG Network
    url: https://github.com/kubernetes/ingress-nginx

icon: https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/docs/images/logo.png